### ISSUE TITLE
Increase build Performance

### ISSUE THREAD

**Issue by hectorerb** [flyve-mdm/web-mdm-dashboard#1081] opened 2018-09-03 13:30 UTC
Hi @flyve-mdm/frontend-development 

We need to use Lazy-Loading and Code-Splitting in the components, to reduce the size of the js files in the build and increase the loading speed of the app

**Comment by Gianfranco97** [comment] 2018-12-13 17:37
Duplicate of https://github.com/flyve-mdm/web-mdm-dashboard/issues/19

**Closed by Gianfranco97** 2018-12-13 17:37 UTC
Labels: performance, refactor
